# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_Mypkg_rcpparma_hello_world`)
}

HuHuCAR_getData <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, omega, p) {
    .Call(`_Mypkg_HuHuCAR_getData`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, omega, p)
}

HuHuCAR_BT_In <- function(data, B, omega, p) {
    .Call(`_Mypkg_HuHuCAR_BT_In`, data, B, omega, p)
}

