// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpparma_hello_world
arma::mat rcpparma_hello_world();
RcppExport SEXP _Mypkg_rcpparma_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpparma_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// HuHuCAR_getData
arma::mat HuHuCAR_getData(int n, unsigned int cov_num, arma::vec level_num, arma::vec pr, std::string type, arma::vec beta, double mu1, double mu2, double sigma, arma::vec omega, double p);
RcppExport SEXP _Mypkg_HuHuCAR_getData(SEXP nSEXP, SEXP cov_numSEXP, SEXP level_numSEXP, SEXP prSEXP, SEXP typeSEXP, SEXP betaSEXP, SEXP mu1SEXP, SEXP mu2SEXP, SEXP sigmaSEXP, SEXP omegaSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type cov_num(cov_numSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type level_num(level_numSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pr(prSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type mu1(mu1SEXP);
    Rcpp::traits::input_parameter< double >::type mu2(mu2SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(HuHuCAR_getData(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, omega, p));
    return rcpp_result_gen;
END_RCPP
}
// HuHuCAR_BT_In
double HuHuCAR_BT_In(arma::mat data, double B, arma::vec omega, double p);
RcppExport SEXP _Mypkg_HuHuCAR_BT_In(SEXP dataSEXP, SEXP BSEXP, SEXP omegaSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(HuHuCAR_BT_In(data, B, omega, p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Mypkg_rcpparma_hello_world", (DL_FUNC) &_Mypkg_rcpparma_hello_world, 0},
    {"_Mypkg_HuHuCAR_getData", (DL_FUNC) &_Mypkg_HuHuCAR_getData, 11},
    {"_Mypkg_HuHuCAR_BT_In", (DL_FUNC) &_Mypkg_HuHuCAR_BT_In, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_Mypkg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
